//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class businessdbEntities : DbContext
    {
        public businessdbEntities()
            : base("name=businessdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<angajati> angajati { get; set; }
        public virtual DbSet<departamente> departamente { get; set; }
        public virtual DbSet<proiecte> proiecte { get; set; }
        public virtual DbSet<tabel_departamente> tabel_departamente { get; set; }
        public virtual DbSet<tabel_proiecte> tabel_proiecte { get; set; }
    
        public virtual int delete_angajat(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_angajat", idParameter);
        }
    
        public virtual int delete_proiect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_proiect", idParameter);
        }
    
        public virtual ObjectResult<membri_proiect_Result> membri_proiect(Nullable<int> proid)
        {
            var proidParameter = proid.HasValue ?
                new ObjectParameter("proid", proid) :
                new ObjectParameter("proid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<membri_proiect_Result>("membri_proiect", proidParameter);
        }
    
        public virtual int minusproiect(Nullable<int> idang, Nullable<int> idpro)
        {
            var idangParameter = idang.HasValue ?
                new ObjectParameter("idang", idang) :
                new ObjectParameter("idang", typeof(int));
    
            var idproParameter = idpro.HasValue ?
                new ObjectParameter("idpro", idpro) :
                new ObjectParameter("idpro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("minusproiect", idangParameter, idproParameter);
        }
    
        public virtual int plusproiect(Nullable<int> idang, Nullable<int> idpro)
        {
            var idangParameter = idang.HasValue ?
                new ObjectParameter("idang", idang) :
                new ObjectParameter("idang", typeof(int));
    
            var idproParameter = idpro.HasValue ?
                new ObjectParameter("idpro", idpro) :
                new ObjectParameter("idpro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("plusproiect", idangParameter, idproParameter);
        }
    
        public virtual int delete_departament(Nullable<int> dep_id)
        {
            var dep_idParameter = dep_id.HasValue ?
                new ObjectParameter("dep_id", dep_id) :
                new ObjectParameter("dep_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_departament", dep_idParameter);
        }
    }
}
